### ISSUE TITLE
Inquiry about Open Sourcing the Scene Construction Code

### ISSUE THREAD

**Issue by gameworm23** [JTRNEO/SynRS3D#1]
Hello! 
Wonderful works! I would like to inquire whether the code related to the Scene Construction section will be made available as open source. Understanding the potential for open sourcing this code would greatly assist me in my research and implementation efforts.

Thank you for your time, and I look forward to your response!

**Comment by JTRNEO** [comment]
Hi! 

Thank you for your interest in our work.

We do have plans to release the code for the Scene Construction part in the future. However, as shown in Table 7 of the appendix, this part relies heavily on commercial Blender plugins, which we have extensively modified. Due to the commercial nature of these plugins, we cannot redistribute the modified versions. As a result, there are two options for releasing the code: the first is to provide documentation on the modifications, which would require considerable time, and the second is to offer the system as an interface, which would also be time-consuming and lack customizability. We are still exploring how to release this part of the code, but it will take time. We appreciate your understanding.

Sincerely,
SONG JIAN

**Comment by gameworm23** [comment]
Thank you for your detailed response. I appreciate the challenges you face with releasing the code that relies on commercial software.

I look forward to any updates on your plans, whether through documentation or an interface. Thanks again for your great work!

**Comment by JTRNEO** [comment]
Thank you again for your understanding.
We have just released the dataset; you are welcome to use it.
If you find them useful, kindly give us a star ⭐!
